services:
  postgres:
    image: "postgres:latest"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U postgres -d postgres'" ]
      interval: 5s
      timeout: 3s
      retries: 3

  pgadmin:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - postgres
